FROM python:3.10.7-slim

# Sets working directory
WORKDIR /assistant

# Copies files and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copies the local chatbot service files
COPY document_store.py /assistant/
COPY info.json /assistant/
COPY functions/.env /assistant/functions/

# Sets the default command for the service
CMD ["python", "document_store.py"]